name: Build Project
on: [push]
jobs:
    windows:
        name: Window build
        runs-on: windows-2022
        steps:
            - uses: actions/checkout@v2
            - name: build
              shell: cmd
              run: ${{'"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && msbuild /p:Configuration=Release'}}
            - name: upload
              uses: actions/upload-artifact@v4
              with:
                name: windows
                path: bin